name: Accessibility Insights

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm ci
      - name: Start development server
        run: npm start
      - name: Run Accessibility Insights
        uses: microsoft/accessibility-insights-action@v3
        with:
          url: http://localhost:3000
          scan-timeout: 1800000
      - name: Upload Accessibility Insights report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
