name: Accessibility Insights

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - name: Start development server
        run: npm start -- &
      - name: Scan site
        uses: double-great/accessibility-scan-action@v0.3.0
        with:
          url: http://localhost:3000
          # scan-timeout: 1800000
      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: "Accessibility report"
          path: ${{ github.workspace }}/_accessibility-reports/index.html
